[package]
name = "sudoku"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3"
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "generate"
harness = false
