[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.25"
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "generate"
harness = false
